### PR TITLE
js utils

### PR DESCRIPTION
**Pull request by wheresrhys**
- Written in ES5 as they should never really be altered and should be used a lot, so we should prioritise performance over elegance of code
- technically a breaking change, but was never documented, and not used anywhere (not sure how the previous `$` got in to master)
- Other ideas for utils to add include 
    - throttle/debounce
    - closest(sel) (closest ancestor matching selector)

@matthew-andrews @keirog @i-like-robots

### CODE REVIEW

**Comment by matthew-andrews** [comment]
+1

**Comment by i-like-robots** [comment]
I'm fully for some utils... is there something off the shelf (http://microjs.com/#dom)?

**Comment by keirog** [comment]
:+1: not sure about off-the-shelf libs for these though

**Comment by wheresrhys** [comment]
patrick suggests https://github.com/ded/bonzo and https://github.com/ded/qwery.

Might be worth copying bits from there in time. My main concern for now was that `document.querySelector[All]` and '[].slice.call' don't minify at all, so rolling out `nUtil.$` and `nUtil.$$` should save us a not insignificant number of bytes

**Pull request merged**
